# Generated by Django 6.0.5 on 2026-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='会社名・屋号')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('message', models.TextField(verbose_name='相談内容')),
                ('diagnosis_area', models.CharField(blank=True, max_length=100, verbose_name='診断時の所在地')),
                ('diagnosis_industry', models.CharField(blank=True, max_length=100, verbose_name='診断時の業種')),
                ('diagnosis_interest', models.CharField(blank=True, max_length=255, verbose_name='診断時の検討内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_handled', models.BooleanField(default=False, verbose_name='対応済み')),
            ],
            options={
                'verbose_name': '問い合わせ',
                'verbose_name_plural': '問い合わせ',
            },
        ),
    ]
