# Generated by Django 6.0.5 on 2026-05-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='diagnosis_programs',
            field=models.TextField(blank=True, verbose_name='候補となった支援策'),
        ),
    ]
