# Generated by Django 6.0.5 on 2026-05-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='制度名')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='実施機関')),
                ('area', models.CharField(blank=True, max_length=255, verbose_name='対象地域')),
                ('target_business', models.TextField(blank=True, verbose_name='対象者・対象事業者')),
                ('purpose_categories', models.JSONField(blank=True, default=list, verbose_name='目的カテゴリ')),
                ('max_amount', models.CharField(blank=True, max_length=100, verbose_name='補助上限額')),
                ('subsidy_rate', models.CharField(blank=True, max_length=100, verbose_name='補助率')),
                ('application_start', models.DateField(blank=True, null=True, verbose_name='公募開始日')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='締切日')),
                ('status', models.CharField(choices=[('open', '募集中'), ('scheduled', '予定'), ('closed', '終了'), ('unknown', '不明')], default='open', max_length=50, verbose_name='ステータス')),
                ('official_url', models.URLField(blank=True, verbose_name='公式URL')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='取得元名')),
                ('source_url', models.URLField(blank=True, verbose_name='取得元URL')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='取得日時')),
                ('raw_text', models.TextField(blank=True, verbose_name='取得時の元テキスト')),
                ('summary', models.TextField(blank=True, verbose_name='概要')),
                ('consultant_comment', models.TextField(blank=True, verbose_name='診断士コメント')),
                ('difficulty', models.IntegerField(default=3, verbose_name='申請難易度')),
                ('recommendation_score', models.IntegerField(default=3, verbose_name='おすすめ度')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '補助金・支援策',
                'verbose_name_plural': '補助金・支援策',
            },
        ),
    ]
